language: c++

matrix:
  include:
    # Clang on OSX
    - env: MATRIX_EVAL="" CONF="--disable-output-uhd"
      os: osx
      osx_image: xcode9.4
      compiler: clang

    - env: MATRIX_EVAL="" CONF=""
      os: osx
      osx_image: xcode9.4
      compiler: clang

    # GCC and clang builds on Linux
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-zeromq --disable-output-uhd"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - libcurl4-openssl-dev
            - libfftw3-dev
            # libuhd-dev is not allowed
            - g++-9

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-output-raw"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --disable-native"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-edi"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-trace"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--enable-easydabv3 --disable-output-uhd --enable-fast-math --disable-native"
      compiler: gcc
      addons: *linuxaddons

before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    brew install fftw || true
    brew install uhd || true
    fi

script:
  - |
    ./bootstrap.sh
    ./configure $CONF
    make

